// Copied from Healthcare.Common / Mis.Common.LoginServiceWrapper (svcutil-generated SOAP client for LGNWS Service.asmx).
// Namespace changed only. Do not edit by hand beyond that.
#nullable disable
#pragma warning disable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sxedia.Web.Auth.LoginService
{


  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
  [System.ServiceModel.ServiceContractAttribute(Namespace = "http://localhost/", ConfigurationName = "ServiceReference1.ServiceSoap")]
  public interface ServiceSoap
  {

    [System.ServiceModel.OperationContractAttribute(Action = "http://localhost/GetUsr", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<Sxedia.Web.Auth.LoginService.User> GetUsrAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://localhost/LogInPComp", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<Sxedia.Web.Auth.LoginService.User> LogInPCompAsync(int category, string ama, string password, string APP, bool B_DEBUG, string computername, string winuser, bool UsePComp);

    [System.ServiceModel.OperationContractAttribute(Action = "http://localhost/LogIn", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<Sxedia.Web.Auth.LoginService.User> LogInAsync(int category, string ama, string password, string APP, bool B_DEBUG, string computername, string winuser);

    [System.ServiceModel.OperationContractAttribute(Action = "http://localhost/GetCategories", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<Sxedia.Web.Auth.LoginService.ArrayOfXElement> GetCategoriesAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://localhost/GetWebApps", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<Sxedia.Web.Auth.LoginService.ArrayOfXElement> GetWebAppsAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://localhost/GetNonWebApps", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<Sxedia.Web.Auth.LoginService.ArrayOfXElement> GetNonWebAppsAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://localhost/ChangePassPComp", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<bool> ChangePassPCompAsync(long userid, string oldpass, string newpass, bool UsePComp);

    [System.ServiceModel.OperationContractAttribute(Action = "http://localhost/ChangePass", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<bool> ChangePassAsync(long userid, string oldpass, string newpass);

    [System.ServiceModel.OperationContractAttribute(Action = "http://localhost/WriteLogDisconnect", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<bool> WriteLogDisconnectAsync(long logonid, bool b_now, System.DateTime DISCONNECTTIME);

    [System.ServiceModel.OperationContractAttribute(Action = "http://localhost/WriteLog", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<int> WriteLogAsync(int GSPERS_ID, int APPLIC_ID, string COMPUTERNAME, string WINDOWSUSER, int STATUS, string USER_NAME, System.DateTime CONNECTTIME, System.DateTime DISCONNECTTIME);

    [System.ServiceModel.OperationContractAttribute(Action = "http://localhost/WriteLogOld", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<int> WriteLogOldAsync(string APPLIC_DESCR, string AMA, string COMPUTERNAME, string WINDOWSUSER, int STATUS, int KATHGORIA_PRS, System.DateTime CONNECTTIME, System.DateTime DISCONNECTTIME);
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://localhost/")]
  public partial class User
  {

    private long userIDField;

    private string userTitleField;

    private long thesiIDField;

    private string thesiField;

    private long monadaField;

    private System.DateTime dtExpField;

    private string aMAField;

    private string passField;

    private string sRV_MSGField;

    private long logonIDField;

    private bool mustChangePasswordField;

    private APP_RIGHT[] aPP_RIGHTSField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public long UserID
    {
      get
      {
        return this.userIDField;
      }
      set
      {
        this.userIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string UserTitle
    {
      get
      {
        return this.userTitleField;
      }
      set
      {
        this.userTitleField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public long ThesiID
    {
      get
      {
        return this.thesiIDField;
      }
      set
      {
        this.thesiIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string Thesi
    {
      get
      {
        return this.thesiField;
      }
      set
      {
        this.thesiField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public long Monada
    {
      get
      {
        return this.monadaField;
      }
      set
      {
        this.monadaField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public System.DateTime DtExp
    {
      get
      {
        return this.dtExpField;
      }
      set
      {
        this.dtExpField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string AMA
    {
      get
      {
        return this.aMAField;
      }
      set
      {
        this.aMAField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public string Pass
    {
      get
      {
        return this.passField;
      }
      set
      {
        this.passField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
    public string SRV_MSG
    {
      get
      {
        return this.sRV_MSGField;
      }
      set
      {
        this.sRV_MSGField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
    public long LogonID
    {
      get
      {
        return this.logonIDField;
      }
      set
      {
        this.logonIDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
    public bool MustChangePassword
    {
      get
      {
        return this.mustChangePasswordField;
      }
      set
      {
        this.mustChangePasswordField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 11)]
    public APP_RIGHT[] APP_RIGHTS
    {
      get
      {
        return this.aPP_RIGHTSField;
      }
      set
      {
        this.aPP_RIGHTSField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://localhost/")]
  public partial class APP_RIGHT
  {

    private long uSER_IDField;

    private string aPP_RIGHT1Field;

    private int aPP_FUNCTION_IDField;

    private string aPP_NAMEField;

    private string aPP_DESCField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public long USER_ID
    {
      get
      {
        return this.uSER_IDField;
      }
      set
      {
        this.uSER_IDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("APP_RIGHT", Order = 1)]
    public string APP_RIGHT1
    {
      get
      {
        return this.aPP_RIGHT1Field;
      }
      set
      {
        this.aPP_RIGHT1Field = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int APP_FUNCTION_ID
    {
      get
      {
        return this.aPP_FUNCTION_IDField;
      }
      set
      {
        this.aPP_FUNCTION_IDField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string APP_NAME
    {
      get
      {
        return this.aPP_NAMEField;
      }
      set
      {
        this.aPP_NAMEField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string APP_DESC
    {
      get
      {
        return this.aPP_DESCField;
      }
      set
      {
        this.aPP_DESCField = value;
      }
    }
  }

  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
  public interface ServiceSoapChannel : Sxedia.Web.Auth.LoginService.ServiceSoap, System.ServiceModel.IClientChannel
  {
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
  public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Sxedia.Web.Auth.LoginService.ServiceSoap>, Sxedia.Web.Auth.LoginService.ServiceSoap
  {

    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

    public ServiceSoapClient(EndpointConfiguration endpointConfiguration) :
            base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
    {
      this.Endpoint.Name = endpointConfiguration.ToString();
      ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
            base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
      this.Endpoint.Name = endpointConfiguration.ToString();
      ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
            base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
      this.Endpoint.Name = endpointConfiguration.ToString();
      ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public System.Threading.Tasks.Task<Sxedia.Web.Auth.LoginService.User> GetUsrAsync()
    {
      return base.Channel.GetUsrAsync();
    }

    public System.Threading.Tasks.Task<Sxedia.Web.Auth.LoginService.User> LogInPCompAsync(int category, string ama, string password, string APP, bool B_DEBUG, string computername, string winuser, bool UsePComp)
    {
      return base.Channel.LogInPCompAsync(category, ama, password, APP, B_DEBUG, computername, winuser, UsePComp);
    }

    public System.Threading.Tasks.Task<Sxedia.Web.Auth.LoginService.User> LogInAsync(int category, string ama, string password, string APP, bool B_DEBUG, string computername, string winuser)
    {
      return base.Channel.LogInAsync(category, ama, password, APP, B_DEBUG, computername, winuser);
    }

    public System.Threading.Tasks.Task<Sxedia.Web.Auth.LoginService.ArrayOfXElement> GetCategoriesAsync()
    {
      return base.Channel.GetCategoriesAsync();
    }

    public System.Threading.Tasks.Task<Sxedia.Web.Auth.LoginService.ArrayOfXElement> GetWebAppsAsync()
    {
      return base.Channel.GetWebAppsAsync();
    }

    public System.Threading.Tasks.Task<Sxedia.Web.Auth.LoginService.ArrayOfXElement> GetNonWebAppsAsync()
    {
      return base.Channel.GetNonWebAppsAsync();
    }

    public System.Threading.Tasks.Task<bool> ChangePassPCompAsync(long userid, string oldpass, string newpass, bool UsePComp)
    {
      return base.Channel.ChangePassPCompAsync(userid, oldpass, newpass, UsePComp);
    }

    public System.Threading.Tasks.Task<bool> ChangePassAsync(long userid, string oldpass, string newpass)
    {
      return base.Channel.ChangePassAsync(userid, oldpass, newpass);
    }

    public System.Threading.Tasks.Task<bool> WriteLogDisconnectAsync(long logonid, bool b_now, System.DateTime DISCONNECTTIME)
    {
      return base.Channel.WriteLogDisconnectAsync(logonid, b_now, DISCONNECTTIME);
    }

    public System.Threading.Tasks.Task<int> WriteLogAsync(int GSPERS_ID, int APPLIC_ID, string COMPUTERNAME, string WINDOWSUSER, int STATUS, string USER_NAME, System.DateTime CONNECTTIME, System.DateTime DISCONNECTTIME)
    {
      return base.Channel.WriteLogAsync(GSPERS_ID, APPLIC_ID, COMPUTERNAME, WINDOWSUSER, STATUS, USER_NAME, CONNECTTIME, DISCONNECTTIME);
    }

    public System.Threading.Tasks.Task<int> WriteLogOldAsync(string APPLIC_DESCR, string AMA, string COMPUTERNAME, string WINDOWSUSER, int STATUS, int KATHGORIA_PRS, System.DateTime CONNECTTIME, System.DateTime DISCONNECTTIME)
    {
      return base.Channel.WriteLogOldAsync(APPLIC_DESCR, AMA, COMPUTERNAME, WINDOWSUSER, STATUS, KATHGORIA_PRS, CONNECTTIME, DISCONNECTTIME);
    }

    public virtual System.Threading.Tasks.Task OpenAsync()
    {
      return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }

    public virtual System.Threading.Tasks.Task CloseAsync()
    {
      return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }

    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
      if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
      {
        System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
        result.MaxBufferSize = int.MaxValue;
        result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
        result.MaxReceivedMessageSize = int.MaxValue;
        result.AllowCookies = true;
        return result;
      }
      if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
      {
        System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
        System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
        textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
        result.Elements.Add(textBindingElement);
        System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
        httpBindingElement.AllowCookies = true;
        httpBindingElement.MaxBufferSize = int.MaxValue;
        httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
        result.Elements.Add(httpBindingElement);
        return result;
      }
      throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
      if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
      {
        return new System.ServiceModel.EndpointAddress("http://10.4.51.250/LGNWS/Service.asmx");
      }
      if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
      {
        return new System.ServiceModel.EndpointAddress("http://10.4.51.250/LGNWS/Service.asmx");
      }
      throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    public enum EndpointConfiguration
    {

      ServiceSoap,

      ServiceSoap12,
    }
  }

  [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny = true)]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.3.0")]
  public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
  {

    private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();

    public ArrayOfXElement()
    {
    }

    public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
    {
      get
      {
        return this.nodesList;
      }
    }

    public virtual System.Xml.Schema.XmlSchema GetSchema()
    {
      throw new System.NotImplementedException();
    }

    public virtual void WriteXml(System.Xml.XmlWriter writer)
    {
      System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
      for (
      ; e.MoveNext();
      )
      {
        ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
      }
    }

    public virtual void ReadXml(System.Xml.XmlReader reader)
    {
      for (
      ; (reader.NodeType != System.Xml.XmlNodeType.EndElement);
      )
      {
        if ((reader.NodeType == System.Xml.XmlNodeType.Element))
        {
          System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
          ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
          Nodes.Add(elem);
        }
        else
        {
          reader.Skip();
        }
      }
    }
  }
}
