<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <Target Name="PostPublishScript" AfterTargets="Publish">
    <Exec Command="cd ..\..\frontend &amp;&amp; npm run build" />
    <Exec Command="robocopy $(ProjectDir)wwwroot $(PublishDir)wwwroot /MIR /LOG:$(PublishDir)robocopy.log" IgnoreExitCode="true" />
  </Target>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="NetVips" Version="3.2.0" />
    <PackageReference Include="NetVips.Native.win-x64" Version="8.18.5" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.300" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

</Project>
